miekg/pkcs11

pkcs11_test.go

Without this, all tests after the first one fail on my box with CKR_CRYPTOKI_ALREADY_INITIALIZED since "Destroy" is invoked before any of the other cleanup functions (due to the LIFO ordering of multiple "defer" invocations in Go).
Happy to modify/refactor/rebase/amend/etc as desired. :+1:

Move session finish actions into a function to ensure proper ordering

---

pkcs11.go

Passing a PIN of NULL is used to indicate that, e.g., PIN
authentication happens outside of the pkcs11 process (through e.g. an
external PIN pad). Since the empty string is generally used as the
absence of a value in Go, convert that to NULL in C.
(I can't entirely discount the possibility that some random device
somewhere actually has a 0-length PIN, but it seems unlikely...)

When attempting to login with an empty PIN, pass to pkcs11 as NULL

---

pkcs11.go

Windows and linux require extra flags to avoid 'dlopen not found' and more compile errors.
Has been tested with `xgo` cross-compilation

Allow compilation with windows,linux,darwin

---

pkcs11_test.go

Fix some small bugs that cause unit tests to fail with SoftHSM v2:
* Correct value for CKO_KEY_TYPE to CKK_RSA. Values for CKO_KEY_TYPE should
be CKK_(RSA|DSA|ECDSA|AES) etc.
* Add CKO_CLASS attribute to correctly set the key type as public or private.

Fix incorrect usage of CKO_KEY_TYPE, add CKO_CLASS

---

pkcs11_test.go

A lot of changes this go-around. I suspect the unit tests worked
previously due to bugs in SoftHSM v1. The biggest problems were
TestFindObject and TestGetAttributeValue failing because they
depended on nonexistent objects. SoftHSM v1 must not have
enforced session based tokens correctly.
* Add token_persistent to generateRSAKeyPair to set the value of
CKA_TOKEN, which determines whether or not a token will be
persistent (stored in the DB) or session based. This is to allow
for persistent token unit tests to be added down the line.
* Add token_label to generateRSAKeyPair, to set the label string
for the token. Useful for debugging which functions are leaving
tokens lying around.
* Add generateRSAKeyPair to TestGetAttributeValue and
TestFindObject. These tests were failing because there …

Fix bugs, add features to work with SoftHSM v2.

---

pkcs11.go
pkcs11_test.go

Avoids an assertion error and stack trace from libtool-ltdl.
Also gofmt pkcs11_test.go.

Check for empty module path

---

types.go

How about this to guard against issue #37 without breaking backwards compatibility?
It's imperfect but should at least reduce the risk.

skip attribute or parameter if it's length is 0 

---

pkcs11.go

This change makes pkcs11 compile on OpenBSD 5.9 (i386).
No further testing yet.

Make it compile on OpenBSD

---

pkcs11.go

Apparently it is enough to specify the struct members names instead of passing them in order. As far as I can tell (with literally no experience in either C or Go programming), the problem has something to do with alignment of data inside the structs on 64 bit systems?
I apologize in advance for not testing this change (and also not really knowing what I'm doing). It compiles but I was not able to run the tests on a windows system due to the missing libsofthsm.

Fix compilation on Windows amd64 (#24)

---

pkcs11.go
pkcs11go.h
types.go

On Windows platforms PKCS#11 requires that all structures be packed
without padding. This would be easy to fix except that cgo apparently cannot interwork with packed structures... so all of the data has to be copied in and out of the structs from C.
Packing requirements are undefined for UNIX platforms which in practice
means leaving the compiler default. I've tried to leave the generated code the same as before for non-Windows targets.
I see other people have been contributing Windows issues/PRs, but I'm curious if they've been having success without fixing the alignment problem. I was getting segfaults and hangs because the pointers in the CK_FUNCTION_LIST were being misinterpreted as either different functions or totally bogus addresses.

Fix structure alignment on windows

---

README.md

Implements crypto.Signer in terms of pkcs11.

Reference thalesignite/crypto11

---

pkcs11.go

PR fixes #63 for Darwin
@miekg

fix LDFLAGS for darwin to avoid go1.9.4 error

---

pkcs11.go

The `--no-as-needed` flag is the default so does not affect compilation.
Go 1.9.4 at least does not like additional cgo flags without extra options.
Fixes Windows and Linux builds.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Remove --no-as-needed from CGo flags

---

params.go
types.go

This adds native support for CK_GCM_PARAM for the AES-GCM mechanism.  This makes it more convenient to pass the parameters to the CKM_AES_GCM mechanism.  
Example usage:
```go
NewMechanism(CKM_AES_GCM, NewGCMParams(iv, aad, 128))
```

Add support for CK_GCM_PARAMS

---

params.go
types.go

After submitting #71 we found this little snippet from Amazon's CloudHSM
documentation:
```
Note
When performing AES-GCM encryption, the HSM ignores the initialization
vector (IV) in the request and uses an IV that it generates. The HSM
writes the generated IV to the memory reference pointed to by the pIV
element of the CK_GCM_PARAMS parameters structure that you supply.
```
This isn't, so far as we can tell, a requirement of the v2.4 standard,
but CloudHSM is already used quite a lot and that will only grow.
This changes the structure to allow pulling out the IV after an encrypt
operation, but with the caveat that manual freeing is necessary. We
didn't see a better way of handling this without significantly changing
the API of the actual PKCS11 calls as they're mapped into the library. …

Modifies the newly-added GCMParams to allow reading IV

---

params.go

This field is required by certain HSM vendor. 
In particular, this enables this library to support Gemalto Network HSM (formally SafeNet Luna).

Fill in ulIvBits when generating CK_GCM_PARAMS.

---

p11/session.go
pkcs11.go
pkcs11_test.go

The previous behavior is not consistent with the specification; the only
way to detect the end of the search is when no objects are returned. In
the future this field should be removed but in the meantime there is no
need to force a breaking change.
Also updates p11.Session.FindObjects to no longer use the deprecated
field, and to handle arbitrarily large result sets.

Deprecate use of boolean return value from FindObjects (#26)

---

pkcs11.go
pkcs11_test.go
types.go

`&data[0]` panics for zero-length arrays.
I considered passing a null pointer (and length word of 0) for empty arrays. I chose not to do this because [many standard C functions (e.g. `memcpy`) forbid this](https://stackoverflow.com/questions/5243012/is-it-guaranteed-to-be-safe-to-perform-memcpy0-0-0), and they may be used internally by the PKCS#11 implementation.

Permit 0-length inputs to Sign(Update), etc

---

p11/session.go

It looks like there was a simple omission of an error return in the `Session.FindObject` method of the `p11` module.

[p11] Return error in Session.FindObject; typo fix.

---

p11/secret_key.go

This adds a simple (copy/paste) set of functionality for objects with `CKA_CLASS` of `CKO_SECRET_KEY`, mirroring the functionality of the `PrivateKey` and `PublicKey` types in the `p11` package.
~[EDIT:] This builds on #98.~

Add `SecretKey` type to `p11` package

---

const.go
params.go
types.go

This PR fixes this issue: https://github.com/miekg/pkcs11/issues/53
- Add struct for CK_ECDH1_DERIVE_PARAMS for use with the CKM_ECDH1_DERIVE mechanism.
- Add KDF constants.
- Support ECDH1DeriveParams in NewMechanism.

Add ECDH1 derive params

---

pkcs11.go

libtool is licensed GPL unless your software is built with libtool, which rather conflicts with the fact that this library is otherwise BSD licensed.
Using `dlopen` on Unix and `LoadLibrary` on Windows is pretty simple as we are not doing anything complicated.
Tested on Linux, OSX and Windows.

Do not use libtool for dynamic library management

---

p11/session.go

First of all thx for the great library, it's really helped me a lot.
The purpose of this PR is to change a bit the session's login API in order to support custom (vendor specific) user types. 
I'm working ATM with SafeNet's Luna SA module and it has support for richer and stricter user model. In order to be able to use its user model one must provide user type in vendor range (above `0x80000000`), so in order to not pollute the library with vendor-specific detail best option seems to be exposition of login method.

Expose login API for vendor specific login types

---

p11/secret_key.go
p11/session.go

This makes it a little easier to use a `Session` to find objects of the desired type, for the common case where you know the class and have the name as a parameter. It also provides an interface that's a little harder to mis-use.
[EDIT:] Builds on #99.

Add typed convenience `Find...` methods to `Session`

---

const.go

Adds two constants, which are useful when looking at token capabilities.
I think `^uint(0)` is as close as we can get to `(~0UL)`, but comments welcome!

Add CK_EFFECTIVELY_INFINITE and CK_UNAVAILABLE_INFORMATION

---

pkcs11.go

https://www.openbsd.org/faq/ports/guide.html#PortsPolicy
libdl functionality is in libc on OpenBSD, so remove -ldl

-ldl not required on OpenBSD

---

p11/module.go

I added it because I sometimes wanted to ctx.Destroy() at p11.

Add p11.Module.Destroy()

---

p11/object.go
p11/session.go

Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
This helps to identify errors from the corresponding calls, which might be a bit more Go "idiomatic" maybe.

p11: return predefined errors

---

types.go

Defer is more expensive than a direct call, and right before a `return` statement is has no effect on the logic.

Remove unnecessary defer from toList() function.

---

params.go
types.go

It is not necessary to copy the memory in order to get a []byte
representation of Go allocated memory, because the GC will take care
of the lifetime of the underlying memory.  This change introduces the
memBytes() function, that returns a slice to an arbitrary memory
area, and replaces all uses of C.GoBytes with Go allocated memory.
This function could even be used for C allocated memory, but then the
caller has to make sure that the underlying C memory is not freed
during the lifetime of the returned slice.
Signed-off-by: Sven Anderson <sven@anderson.de>

Remove unnecessary memory copies by C.GoBytes() calls

---

p11/slot.go

I chose to add 2 methods instead of exporting the pkcs11.Mechanism because this way the calling code is less verbose, i.e. `mechanism.Type()` instead of `mechanism.Mechanism.Mechanism`.
Fixes https://github.com/miekg/pkcs11/issues/158

p11: Add Mechanism.Type() and Mechanism.Parameter()

---

p11/module.go

While using softhsm in some tests, I ran into issues while re-using the same pkcs11 context. Calling `module.Destroy` together with these fixes allow me to use the p11 module (instead of going all in on the raw pkcs11 interface).
* Returns `error` from the `Module.Destroy` in p11. This is an API change. I can remove this if wanted.
* Calls `ctx.Finalize` before calling `ctx.Destroy` in `Module.Destroy`
This allow a more graceful unloading of modules. I suspect there are multiple reasons why you didn't do this before? At least removing the loaded module from the map should improve a lot.

Call Finalize on Module destroy

---

params.go
types.go

Mechanism implementation:
https://github.com/OP-TEE/optee_os/pull/5647
pkcs11-spec-v3.1-cs01
6.1.23 RSA AES KEY WRAP
The RSA AES key wrap mechanism based on the RSA public-key cryptosystem and the AES key wrap mechanism. It supports single-part key wrapping and key unwrapping.
How to use:
```
params := &pkcs11.RSAAESKeyWrapParams{
AESKeyBits: 256,
OAEPParams: pkcs11.OAEPParams{
HashAlg:    pkcs11.CKM_SHA256,
MGF:        pkcs11.CKG_MGF1_SHA256,
SourceType: pkcs11.CKZ_DATA_SPECIFIED,
},
}
mechanism := []*pkcs11.Mechanism {
pkcs11.NewMechanism(pkcs11.CKM_RSA_AES_KEY_WRAP, params)
}
unwrappedKey, err := ctx.UnwrapKey(session, mechanism, wrappingKeyObj,
wrappedKey, unwrappedKeyAttributes)
```

Add RSA AES key wrap mechanism parameters

---

const_generate.go
zconst.go

The PKCS11 constants are most useful when creating attributes with
`NewAttribute()` in all kinds of different PKCS11 calls. The function
is using generic type handling to decide attribute length.
The CK_TRUE/CK_FALSE constants should evaluate to direct Golang
bool values in order for these to be handled properly by the
`NewAttribute()` calls, which interprets bool values as
[]byte{0}, []byte{1} for false, true respectively. If these stay
integers, `NewAttribtue()` considers them 8-byte long byte slices.
Some PKCS11 module implementations actually validate constant-length
arguments size. https://github.com/opendnssec/SoftHSMv2/ is an example
of a commonly used PKCS11-testing module that does that. Without this
change, the module fails to perform certain actions as it errors out
on …

const_generate: hardcode CK_TRUE/CK_FALSE to golang bool values
